# Generated by Django 5.2.7 on 2025-10-10 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'approval',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cano', models.IntegerField(blank=True, null=True)),
                ('cname', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'candidate',
            },
        ),
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctitle', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'db_table': 'criteria',
            },
        ),
        migrations.CreateModel(
            name='EsLogUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'esloguser',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evdes', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Gradinsname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(blank=True, max_length=50)),
                ('lname', models.CharField(blank=True, max_length=50)),
                ('ulevel', models.CharField(blank=True, max_length=5)),
            ],
            options={
                'db_table': 'gradinsname',
            },
        ),
        migrations.CreateModel(
            name='Gradminpas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50)),
                ('spassword', models.CharField(blank=True, max_length=128)),
            ],
            options={
                'db_table': 'gradminpas',
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jname', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'judge',
            },
        ),
        migrations.CreateModel(
            name='JudgeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'judgeapproval',
            },
        ),
        migrations.CreateModel(
            name='Judgecriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejid', models.IntegerField(blank=True, null=True)),
                ('scri', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'judgecriteria',
            },
        ),
        migrations.CreateModel(
            name='Judgesapproved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejid', models.IntegerField(blank=True, null=True)),
                ('evid', models.IntegerField(blank=True, null=True)),
                ('sconid', models.IntegerField(blank=True, null=True)),
                ('aprem', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'judgesapproved',
            },
        ),
        migrations.CreateModel(
            name='Resall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sconid', models.IntegerField(blank=True, null=True)),
                ('evid', models.IntegerField(blank=True, null=True)),
                ('ejid', models.IntegerField(blank=True, null=True)),
                ('scri', models.IntegerField(blank=True, null=True)),
                ('inscore', models.CharField(blank=True, max_length=6, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'resall',
            },
        ),
        migrations.CreateModel(
            name='Rescri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sconid', models.IntegerField(blank=True, null=True)),
                ('evid', models.IntegerField(blank=True, null=True)),
                ('ejid', models.IntegerField(blank=True, null=True)),
                ('scri', models.IntegerField(blank=True, null=True)),
                ('inscore', models.CharField(blank=True, max_length=6, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'rescri',
            },
        ),
        migrations.CreateModel(
            name='Resnoshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noshow', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'resnoshow',
            },
        ),
        migrations.CreateModel(
            name='SAdmin',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('userlevel', models.CharField(blank=True, max_length=5, null=True)),
                ('uname', models.CharField(blank=True, max_length=50, null=True)),
                ('spassword', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sadmin',
            },
        ),
        migrations.CreateModel(
            name='Scorevents',
            fields=[
                ('evid', models.AutoField(primary_key=True, serialize=False)),
                ('evdes', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'scorevents',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0)),
                ('candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.candidate')),
            ],
            options={
                'db_table': 'score',
            },
        ),
        migrations.CreateModel(
            name='SCandidates',
            fields=[
                ('sconid', models.AutoField(primary_key=True, serialize=False)),
                ('cano', models.IntegerField(blank=True, null=True)),
                ('cname', models.CharField(blank=True, max_length=100, null=True)),
                ('course', models.CharField(blank=True, max_length=10, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('canstatus', models.CharField(blank=True, max_length=2, null=True)),
                ('evid', models.ForeignKey(blank=True, db_column='evid', null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.scorevents')),
            ],
            options={
                'db_table': 'scandidates',
            },
        ),
        migrations.CreateModel(
            name='Scri',
            fields=[
                ('scri', models.AutoField(primary_key=True, serialize=False)),
                ('ctitle', models.CharField(blank=True, max_length=50, null=True)),
                ('cper', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=2, null=True)),
                ('minrate', models.CharField(blank=True, max_length=4, null=True)),
                ('evid', models.ForeignKey(blank=True, db_column='evid', null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.scorevents')),
            ],
            options={
                'db_table': 'scri',
            },
        ),
        migrations.CreateModel(
            name='SJudge',
            fields=[
                ('ejid', models.AutoField(primary_key=True, serialize=False)),
                ('jname', models.CharField(blank=True, max_length=100, null=True)),
                ('uname', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('spassword', models.BinaryField(blank=True, null=True)),
                ('evid', models.ForeignKey(blank=True, db_column='evid', null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.scorevents')),
            ],
            options={
                'db_table': 'sjudge',
            },
        ),
        migrations.CreateModel(
            name='Sinscore',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inscore', models.CharField(blank=True, default='0', max_length=6, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('subdon', models.CharField(blank=True, default='0', max_length=2, null=True)),
                ('cristat', models.CharField(blank=True, max_length=2, null=True)),
                ('rankscore', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('evid', models.ForeignKey(blank=True, db_column='evid', null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.scorevents')),
                ('sconid', models.ForeignKey(blank=True, db_column='sconid', null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.scandidates')),
                ('scri', models.ForeignKey(blank=True, db_column='scri', null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.scri')),
                ('ejid', models.ForeignKey(blank=True, db_column='ejid', null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.sjudge')),
            ],
            options={
                'db_table': 'sinscore',
            },
        ),
        migrations.AddField(
            model_name='scandidates',
            name='ejid',
            field=models.ForeignKey(blank=True, db_column='ejid', null=True, on_delete=django.db.models.deletion.RESTRICT, to='mainapp.sjudge'),
        ),
    ]
