# Generated by Django 5.2.7 on 2025-10-11 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.event'),
        ),
        migrations.AddField(
            model_name='judge',
            name='uname',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
